### ISSUE TITLE
High-level extension lifecycle planning and best practices

### ISSUE THREAD

**Issue by otherjoel** [hougaard/Simple-Object-Designer#170]
Do you have a video or blog post collecting some basic best practices for using Simple Object Designer?

* Any planning steps to take ahead of implementing new fields/features?
* How should I think of various kinds of changes implemented with Simple Object Designer: once implemented and used in production, are they best considered “set in stone”, never to be altered? How careful do I need to be?
* How should sets of unrelated changes be bundled? I.e., if I have a set of changes to Item cards from the engineering team and another set of changes to Sales documents from the operations folks, can/should I implement those separately, and if so what is the method for doing so?
* From testing to production: Is it possible to deploy in a sandbox environment and then “transfer” the tested extension to Simple Object Designer in production, or do I simply need to manually recreate the same changes in the production environment? If so, how are changes handled after the initial deployment?

**Comment by hougaard** [comment]
> Do you have a video or blog post collecting some basic best practices for using Simple Object Designer?

Not a "best practice" video,  but that's a really good idea.

> * Any planning steps to take ahead of implementing new fields/features?

The usual one, make sure standard BC doesn't solve what you want. But in general, play in a sandbox, that's what it's there for :)

> * How should I think of various kinds of changes implemented with Simple Object Designer: once implemented and used in production, are they best considered “set in stone”, never to be altered? How careful do I need to be?

You should avoid situations where you need to turn on the "Force" deploy setting because that can result in data loss. But if you created a field that you no longer need and want to get rid of the field, data loss can be OK.

> * How should sets of unrelated changes be bundled? I.e., if I have a set of changes to Item cards from the engineering team and another set of changes to Sales documents from the operations folks, can/should I implement those separately, and if so what is the method for doing so?

In general, I'm a big fan of a single app, keep it simple when possible. The biggest reason to split is to avoid circular dependencies. (If you have a partner app that you have a dependency to, and the partner need to be dependent on your app).

> * From testing to production: Is it possible to deploy in a sandbox environment and then “transfer” the tested extension to Simple Object Designer in production, or do I simply need to manually recreate the same changes in the production environment? If so, how are changes handled after the initial deployment?

"Best practice" is to do your development in a sandbox, deploy your app to the sandbox, and test it there. And when you're happy with the result, take the .app file produced and upload it to production (via extension management page).

**Comment by otherjoel** [comment]
Thanks, much appreciated. I’m just getting started “self-serving” customizations and this is a great way to start. At the same time, I’m concerned that I start out right, and not do anything irreversible that might come back to bite me later on.
