### ISSUE TITLE
Make fields mandatory

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#19]
Hello Erik,

Is it possible in SOD to make a field mandatory?

I tried looking through the app but couldn't find anything.

**Comment by hougaard** [comment]
Due to the way BC works, (without a "Save" button), it's really hard to implement in a nice way. Even the mandatory fields from Microsoft (marked with a red asterisk) are not _mandatory_ , they just look like it and then there may be code later on that verifies it.

There are some who tries to enforce it via global triggers, but that's a really bad design.

**Comment by ScottB-Ronco** [comment]
OK thank you, so I guess that means currently this is not possible withing SOD correct?

If so then this issue can be closed.

**Comment by hougaard** [comment]
Correct.
