### ISSUE TITLE
Install Same version of App after update

### ISSUE THREAD

**Issue by ScottB-Ronco** [hougaard/Simple-Object-Designer#99]
We face an issue with our sandbox system that every time it gets updated it removes all extensions (standard action by Microsoft).

Now I need to installed the app file again, but because the last version of the app I published was already installed it fails.

How can we reinstall an app without having to go into SOD and publish again to create a new version?

**Comment by hougaard** [comment]
No, Microsoft is removing all "DEV" deployed extensions. Your app from SOD is deployed with "PTE" scope and will not be deleted..... unless... If you depend on a DEV deployed extension, your app will be removed because it cannot work without the DEV app being there.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/3357237/184471754-949ae893-27dd-41ad-a8b7-b650204178f1.png">

**Comment by ScottB-Ronco** [comment]
Yes my app does have some dependencies on a other DEV apps created by our partner who does larger scope projects.

With that is there any way around this?

**Comment by hougaard** [comment]
Please report this issue at hougaard.com/support if this is still an issue
